import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#858383",
        "surface-container-low": "#f5f3f3",
        "surface-variant": "#e4e2e2",
        "tertiary-container": "#1c1c19",
        "primary-fixed": "#e5e2e1",
        error: "#ba1a1a",
        "on-surface-variant": "#444748",
        "surface-bright": "#fbf9f9",
        outline: "#747878",
        "surface-container-highest": "#e4e2e2",
        "on-tertiary-fixed-variant": "#474743",
        "tertiary-fixed": "#e5e2dd",
        "surface-container": "#efeded",
        "on-secondary-fixed-variant": "#574500",
        "on-error": "#ffffff",
        "surface-dim": "#dbdad9",
        secondary: "#735c00",
        "inverse-surface": "#303031",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e9e8e7",
        "tertiary-fixed-dim": "#c9c6c2",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary-fixed": "#241a00",
        "surface-tint": "#5f5e5e",
        "secondary-fixed-dim": "#e9c349",
        "on-primary-fixed-variant": "#474746",
        "on-secondary-container": "#745c00",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1c1c19",
        "on-tertiary-container": "#858480",
        "on-surface": "#1b1c1c",
        "inverse-on-surface": "#f2f0f0",
        "primary-fixed-dim": "#c8c6c5",
        "outline-variant": "#c4c7c7",
        "primary-container": "#1c1b1b",
        background: "#fbf9f9",
        primary: "#000000",
        surface: "#fbf9f9",
        "on-background": "#1b1c1c",
        tertiary: "#000000",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "inverse-primary": "#c8c6c5",
        "on-primary": "#ffffff",
        "secondary-container": "#fed65b",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffe088",
        "gold-luxury": "#D4AF37",
        "gold-dark": "#b8952e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        unit: "8px",
      },
      fontFamily: {
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        playfair: ["Playfair Display", "serif"],
        hanken: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
